; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:sender]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<../src_sender/>
lib_deps = 
	olikraus/U8g2 @ ^2.36.0
	adafruit/Adafruit MPU6050 @ ^2.2.6
	adafruit/Adafruit Unified Sensor @ ^1.1.15
	adafruit/DHT sensor library @ ^1.4.6

[env:receiver]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<../src_receiver/>
lib_deps = 
	olikraus/U8g2 @ ^2.36.0
	adafruit/Adafruit MPU6050 @ ^2.2.6
	adafruit/Adafruit Unified Sensor @ ^1.1.15
	adafruit/DHT sensor library @ ^1.4.6


[env:env1]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
lib_deps = 
	olikraus/U8g2 @ ^2.36.0
	adafruit/Adafruit MPU6050 @ ^2.2.6
	adafruit/Adafruit Unified Sensor @ ^1.1.15
	adafruit/DHT sensor library @ ^1.4.6